caseDetailsHeaders = {
        'Accept': '*/*',
        'Accept-Encoding': 'gzip, deflate, br, zstd',
        'Accept-Language': 'en-US,en;q=0.6',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
        # 'Cookie': f'cookiesession1={cookiesession1}; ci_session={ci_session}',
        'Cookie': 'cookiesession1=678A8C315011D85457FAD05CFEDD00D8; ci_session=ln4c49qcdaehpulaivasl60t40f6jn63',
        'Host': 'allahabadhighcourt.in',
        'Origin': 'https://allahabadhighcourt.in',
        'Pragma': 'no-cache',
        'Referer': 'https://allahabadhighcourt.in/apps/status_ccms/index.php/party-name',
        'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Brave";v="126"',
        'Sec-Ch-Ua-Mobile': '?0',
        'Sec-Ch-Ua-Platform': '"Windows"',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
        'Sec-Gpc': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
        'X-Requested-With': 'XMLHttpRequest'
    }